export type MobilityTrend = "improving" | "stable" | "declining";
export type RiskLevel = "low" | "medium" | "high" | "critical";
export interface MobilitySource { id: string; name: string; agency: string; description: string; url?: string; lastUpdated: string; }
export interface MobilityMetric { key: string; label: string; value: number; unit: "%" | "$" | "score" | "minutes" | "permits" | "index"; direction: "up" | "down" | "flat"; interpretation: "positive" | "negative" | "neutral"; delta?: number; sourceIds: string[]; }
export interface MobilityLocation { id: string; name: string; county: string; type: "city" | "neighborhood" | "tract"; latitude: number; longitude: number; population: number; mobilityScore: number; mobilityTrend: MobilityTrend; riskLevel: RiskLevel; medianIncome: number; rentBurden: number; jobAccessScore: number; transitAccessScore: number; schoolAccessScore: number; housingProductionIndex: number; commuteBurdenMinutes: number; displacementRiskScore: number; povertyPressureScore: number; opportunityDelta: number; summary: string; primaryDrivers: string[]; factSource: string; sourceUrl?: string; metrics: MobilityMetric[]; }
export interface TimeSeriesPoint { year: number; rentBurden: number; medianIncome: number; commuteBurdenMinutes: number; housingPermits: number; mobilityScore: number; displacementRiskScore: number; }
export interface CompareResult { left: MobilityLocation; right: MobilityLocation; deltas: { mobilityScore: number; rentBurden: number; medianIncome: number; commuteBurdenMinutes: number; displacementRiskScore: number; housingProductionIndex: number; }; summary: string; }
export interface CommandResponse { command: string; intent: "compare" | "scan" | "show" | "rank" | "report" | "unknown"; response: string; locations?: MobilityLocation[]; compare?: CompareResult; warnings?: string[]; }
export interface MobilityReport { title: string; locationName: string; executiveSummary: string; findings: string[]; recommendedUses: string[]; sources: MobilitySource[]; generatedAt: string; }
